FROM golang:1.23-alpine

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o ./bin/main ./cmd/main

ENV SERVER_ADDRESS=0.0.0.0:8080
ENV POSTGRES_CONN=
ENV POSTGRES_JDBC_URL=
ENV POSTGRES_USERNAME=
ENV POSTGRES_PASSWORD=
ENV POSTGRES_HOST=
ENV POSTGRES_PORT=
ENV POSTGRES_DATABASE=

EXPOSE 8080

CMD ["./bin/main"]

